title: 💸 Scrambly Dollar
description: Chaotic good, slightly unhinged, genuinely helpful
author: Scrambly Dollar
email: scramblydollar@firemail.cc
url: "https://411339.github.io/scrambly-dollar-blog"
baseurl: "/scrambly-dollar-blog"
theme: jekyll-theme-hacker

show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-sitemap